// USER SIGN IN
export const SIGNIN_USER_SUCCESSFULY = 'SIGNIN_USER_SUCCESSFULY'
export const SIGNIN_USER_ERROR = 'SIGNIN_USER_ERROR'

// USER SIGN UP
export const SIGNUP_USER_SUCCESSFULY = 'SIGNUP_USER_SUCCESSFULY'
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR'


// PRODUCT REGISTER
export const REGISTER_PRODUCT_SUCCESSFULY = 'REGISTER_PRODUCT_SUCCESSFULY'
export const REGISTER_PRODUCT_ERROR = 'REGISTER_PRODUCT_ERROR'


// LIST PRODUCTS
export const LIST_PRODUCT_SUCCESSFULY = 'LIST_PRODUCT_SUCCESSFULY'
export const LIST_PRODUCT_ERROR = 'LIST_PRODUCT_ERROR'


// EDIT PRODUCT
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR'


// UPDATE PRODUCT
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR'


// DELETE PRODUCT
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR'

